## Synthetic population pipeline for California
## based on the synpp package

# This is the path to a directory where the pipeline can store temporary data
working_directory: /nas/balacm/California/cache_sf

# This section defines which parts of the pipeline should be run
run:
  #- data.spatial.zones
  #- data.census.cleaned
  #- data.osm.add_pt_variable
  #- data.education.education_facilities
  #- data.hts.cleaned
  #- data.od.raw
  #- synthesis.population.sampled
  #- synthesis.population.matching
  #- synthesis.population.trips
  #- synthesis.population.spatial.by_person.primary_zones
  #- synthesis.population.spatial.by_person.primary_locations_education
  #- synthesis.population.spatial.by_person.secondary.locations
  #- synthesis.output # To create the output population in the output_path (see below)
  #- synthesis.population.spatial.locations
  #- synthesis.population.sociodemographics
  #- matsim.scenario.population
  #- matsim.scenario.supply.processed
  #- synthesis.population.spatial.by_person.secondary.distance_distributions
  #- synthesis.destinations
  #- matsim.simulation.run
  #- matsim.scenario.supply.gtfs
  - matsim.runtime.eqasim
  #- matsim.output # Uncomment, if you want to run the full simulation (you'll need Java for that)
  #- analysis.analysis
# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 24

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.01
  random_seed: 1234

  # define regions to be synthesized
  counties: [1.0, 13.0, 41.0, 55.0, 75.0, 81.0, 85.0, 95.0, 97.0]
  #counties: [73.0]
  county_names: ["Alameda","Contra Costa","Marin","Napa","San Francisco","San Mateo","Santa Clara","Solano","Sonoma"]
  #county_names: ["San Diego"]
  zones: ['001', '075', '085', '081', '095', '097', '013', '041', '055']
  #zones: ['073']
  minimum_source_samples: 4
  spatial_file: "SF_Bay_Area_cleaned.shp"
  osm_file: "sf_bay.osm.pbf"
  # Paths to the input data and where the output should be stored
  data_path: /nas/balacm/California/Data/SF
  output_path: /nas/balacm/California/output/SF

  # Only interesting if you run the simulation
  java_memory: 100G

  # Only interesting if the analysis script is run
  analysis_path: /nas/balacm/California/Analysis/SD